### PR TITLE
Better UX/UI

### LINKED ISSUE #5: Loop menu
Hello,

I was thinking about adding a Loop menu (one of the TODOs in the code).
This way it doesn't exit abruptly if you write a wrong command.

Something similar to:

```python
def menu(account_data, client, board, session):
    player_username = account_data["username"]
    print("Welcome to Lichess {}!".format(player_username))

    while True:
        print("""
        P to play
        H for help
        Q to quit
        """)
        ans = input("command: ").lower()

        if ans.lower== "q":
            sys.exit()

```

This use the player would also go back to the menu after a game, maybe change a configuration, token, etc.

I can try to remake the current menu in this format so we can test it out before adding new features.

### LINKED ISSUE #15: Library security patches
I recommend using https://dependabot.com/ to automatically apply library security patches.

### PR DESCRIPTION
**Pull request by samthegitguy**
Fixes #5 and fixes #15
Still draft PR when I add other loops for other inputs i'll mark as ready to review

### CODE REVIEW

**Comment by Cqsi** [comment]
Hey!
Sorry for reaching out to you a little late. 

I read from your profile that your interested in contributing to other people's projects. This is a project that you can contribute however much you want to, because it's not actively being worked on by pretty much anyone (that doesn't mean people don't use this program!)

Thanks a lot for your contribution. For the moment your changes look perfectly fine, but I'll have to take a closer look still tomorrow before I merge the pull request.

**Comment by samthegitguy** [comment]
No problem! I'll mark it as ready soon.

**Comment by Cqsi** [comment]
Hey!
Nice additions, I love them! There's one problem tho, the Github check failed, and threw the following error:
`Run # stop the build if there are Python syntax errors or undefined names
./lichs/__main__.py:55:13: F823 local variable 'input' defined as a builtin referenced before assignment
    input = input("Choose your option: ")
            ^
1     F823 local variable 'input' defined as a builtin referenced before assignment
1
Error: Process completed with exit code 1.`

Would it be possible for you to change the input variable name to something else? I would have thought it works (and checking in a python environment, it still seems to work?), but apparently Github throws and error.

**Comment by samthegitguy** [comment]
No problem! It might be a problem with the input function being named the same as the variable. Changed now in samthegitguy@e503421 , and I've enabled Actions for my fork so I should have better hindsight now :) Also fixed a bunch of bugs I didn't realise earlier in that commit.

**Comment by Cqsi** [comment]
Everything seemed good, so I merged it to the master branch. Don't worry if you didn't add everything you wanted, you can continue committing. By merging this it makes it a little easier for me.

**Comment by Cqsi** [comment]
Oops, I accidentally merged this, but I reverted it.

**Comment by Cqsi** [comment]
By the way is your code ready to be merged or? Because I looked through it, there's a small amount of stuff I would like to change (readability etc)

**Comment by samthegitguy** [comment]
FYI issues #15 and #5 got closed with merging so you might want to reopen those, at least until this is actually merged. Anyway, if there's anything you'd like to change, i've given you access to my repo. I might make some edits later too.

**Comment by samthegitguy** [comment]
I've fixed readability best I can but you're welcome to add anything else. Ready for merging when you're done.

**Pull request merged**
