### PR TITLE
Revert "Revert "Better UX/UI""

### PR DESCRIPTION
**Pull request by samthegitguy**
Reverts Cqsi/lichs#19

### CODE REVIEW

**Comment by samthegitguy** [comment]
Opened again

**Comment by Cqsi** [comment]
Alright, I merged this now. It looked good, but I might change some things, like for example; why in the if-statements do you check for example `if string.lower() == "A"` instead of just directly checking `if string == "P"`? I just want to know if there was some idea behind it.

**Comment by Cqsi** [comment]
I also still need to update the project on PyPi so if you download it now the update hasn't come yet.

**Comment by samthegitguy** [comment]
Using `string.lower()` is usually used when getting user input, because if the user gives p or P, both will become p and will be validated. Any other questions, let me know

**Comment by Cqsi** [comment]
Yeah alright, that's good. Then one other thing; what did you change with the `token_file` variable? What's the difference between your change and what it was before?

**Comment by samthegitguy** [comment]
A really minor change - I just changed `key` to `token.key` , a little more descriptive, (it's a token and it's a key)

**Comment by samthegitguy** [comment]
And the key file extension is used for storing keys

**Comment by Cqsi** [comment]
Alright, thanks for your contributions. I'm going to updated the PyPi repo now.

**Comment by samthegitguy** [comment]
Thanks!

**Pull request merged**
